/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        // Copy and paste your answer from CodingBat appropriatley here.
  for (long i = 2; i <= Math.sqrt(n); i++){
    if (n % i == 0){
      return false;
    }
  }
  return true;
}
    
    public long firstPrimeNumberIn(String n) {
        // Write your code here.
        for (int i = 0; i < n.length()-10; i++){
            
            if (isPrime(Long.parseLong(n.substring(0,10))) == true){
                return Long.parseLong(n.substring(0,10));
            } 
        }
        return -1;
    }
}

